### ISSUE TITLE
[Bug] Category ID is the same across all flights

### ISSUE THREAD

**Issue by kndoshn** [getditto/demoapp-skyservice#13]
## Problem
- there's a bug that category IDs are the same across all flights
- this may cause issues if users test on multiple flights

## Severity
- medium
    - this seems to have existed since day one
    - this doesn't affect users who test on a single flight

## Work estimate
- one-to-two person-days, including manual tests

**Comment by okdistribute** [comment]
I believe this is intentional because an airline company with the same in-flight offering would want to share that across flights.

**Comment by kndoshn** [comment]
I should have added more contexts, sorry!

## Current behavior:

- The "categories" collection is subscribed on a query with `workspaceId` (this defines which flight you're logged in)
    - A category added on a flight cannot be seen on other flights
- Menu Items are not shared across flights, but categories are.
- Prepopulate categories are added with the `insertIfAbsent` write strategy, but since the Document IDs are the same, this will be ignored when logging in to other flights because it already exists

https://github.com/getditto/demoapp-skyservice/blob/34f551fc360a8b01121db74ed279084afb0e627c/iOS/SkyService/Data/DataService/DataService.swift#L366

https://github.com/getditto/demoapp-skyservice/blob/34f551fc360a8b01121db74ed279084afb0e627c/iOS/SkyService/Data/DataService/DataService%2BPrepopulate.swift#L326

## Problems
1. Categories won't be synced except on the flight on which it's added because of the query
2. Prepopulate categories don't work as expected (can't be added on other flights)

## Solution
-  🤔 Categories can be synced by removing `workspaceId == '\(workspaceId)'` in the query. However, this can cause other issues:
    - They will be synced among **all users**. This is a demo app and is expected to be used by many users, so someone could mess up the data
    - Menu Items are not shared between different flights anyway
- My current thoughts:
    - Do not specify a Document ID to a category; use the random ID which the Ditto SDK generates
    - Use "category names" on menu items to specify the item's category.

**Comment by okdistribute** [comment]
That makes sense! Thanks for the proposal
