### ISSUE TITLE
Soft delete instead of remove()

### ISSUE THREAD

**Issue by kndoshn** [getditto/demoapp-skyservice#2]
## What we have now
SkyService iOS crew, passenger, and Android passenger apps are using the Ditto SDK `remove()` API.

|remove() calls|
|--|
|![image](https://user-images.githubusercontent.com/26117257/223033679-4211c039-08f1-4658-a174-97312e26fa27.png)|

## How we want to change

We recommend customers for doing soft delete instead of calling `remove()` for deleting data. ([See Slack conversation for contexts](https://dittolive.slack.com/archives/C0493F7124C/p1675641821973839)).

1. Do not use `remove()` in iOS and Android apps
2. Have delete flags on models
3. Toggle the flag to hide data from apps
4. Use query to avoid syncing deleted Documents

```swift
struct Note {
  let _id: String
  var text: String
  var deleted: Bool
}

// deleting data
note.deleted = true 

// finding data
collection.find("deleted == false")
```

## Targets

- iOS Crew app
- iOS Passenger app
- Android Passenger app

**Comment by kndoshn** [comment]
@texasRanger09 Do you think you have time to take this issue?

**Comment by texasRanger09** [comment]
Yep, I can take it
