### ISSUE TITLE
SkyService android auth client should be kept in scope

### ISSUE THREAD

**Issue by okdistribute** [getditto/demoapp-skyservice#23]
All authDelegates should be kept as a variable (see iOS, which does this correctly)

[offending line](https://github.com/getditto/demoapp-skyservice/blob/main/Android/app/src/main/java/live/dittolive/skyservice/SkyServiceApplication.kt#L42)

**Comment by abunur** [comment]
related to https://github.com/getditto/demoapp-skyservice/issues/24
