### ISSUE TITLE
POS/KDS skin

### ISSUE THREAD

**Issue by okdistribute** [getditto/demoapp-skyservice#31]
* "Seat" -> "Table"
* "Flight ID" -> "Restaurant Location"
* Don't need a date for login
* Name of the app
* Different colors will help people visually discern the two apps quickly (white background with yellow or red?)

**Comment by kndoshn** [comment]
The app is mostly done and pushed in
- https://github.com/getditto/demoapp-pos-kds

**Comment by okdistribute** [comment]
Thanks @kndoshn! When you're ready to publish to the app store, please do. Feel free to add any improvements you see fit but we need it published to the App Store by May 19
